version: '3'

services:
  server1:
    image: ubuntu-ansible
    container_name: server1
    ports:
      - "2201:22"
    tty: true

  server2:
    image: ubuntu-ansible
    container_name: server2
    ports:
      - "2202:22"
    tty: true

  server3:
    image: ubuntu-ansible
    container_name: server3
    ports:
      - "2203:22"
    tty: true

  server4:
    image: ubuntu-ansible
    container_name: server4
    ports:
      - "2204:22"
    tty: true

  server5:
    image: ubuntu-ansible
    container_name: server5
    ports:
      - "2205:22"
    tty: true
